spring:
  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    platform: postgres
    hikari:
      conntection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER